(function(){
  "use strict";
  var BOOKING="https://booking2.softtec.software/volapuekkonstanz";
  var page=document.body.getAttribute("data-page")||"home";
  var nav=[["zimmer","Zimmer","zimmer/"],["angebote","Angebote","arrangements/"],["wellness","Wellness","wellness/"],["restaurant","Restaurant","restaurant/"],["erleben","Bodensee erleben","erleben/"],["planen","Aufenthalt planen","hotelinfos/"]];
  function current(key){return page===key?' aria-current="page"':''}
  function navHtml(){return nav.map(function(n){return '<a href="'+n[2]+'"'+current(n[0])+'>'+n[1]+'</a>'}).join("")}
  function header(){return '<a class="skip-link" href="#inhalt">Zum Inhalt</a><div class="topline"><div class="topline__inner"><span><a href="tel:+49753194400">+49 7531 94400</a><a href="mailto:info@volapuek.de">info@volapuek.de</a></span><span>Kostenfrei parken · Sauna inklusive · Mainau zu Fuß</span></div></div><header class="site-header"><div class="nav-shell"><a class="brand" href="./" aria-label="Hotel Volapük Startseite"><img src="img/logo-volapuek.png" alt="Logo Hotel Volapük"><span class="brand__text"><strong>Volapük</strong><small>Hotel · Restaurant · Konstanz</small></span></a><nav class="main-nav" id="mainNav" aria-label="Hauptnavigation">'+navHtml()+'</nav><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mainNav">Menü</button><a class="button nav-cta" href="'+BOOKING+'" target="_blank" rel="noopener">Verfügbarkeit prüfen</a></div></header><a class="mobile-book" href="'+BOOKING+'" target="_blank" rel="noopener">Zimmer & Preise prüfen</a>'}
  function footer(){return '<section class="cta-band"><div class="cta-band__inner"><div><h2>Der See ist nah. Ihr Zimmer auch.</h2><p>Verfügbarkeit und aktuelle Preise direkt beim Hotel prüfen.</p></div><a class="button button--light" href="'+BOOKING+'" target="_blank" rel="noopener">Direkt buchen</a></div></section><footer class="site-footer"><div class="footer-main"><div class="footer-logo"><img src="img/logo-volapuek.png" alt="Logo Hotel Volapük"><p>Familiengeführt, im Grünen und mit Blick über den Überlinger See.</p></div><div class="footer-col"><h3>Entdecken</h3><a href="zimmer/">Zimmer & Preise</a><a href="arrangements/">Arrangements</a><a href="wellness/">Wellness & Day Spa</a><a href="restaurant/">Restaurant Litzel\'s</a><a href="bilder/">Bilderwelten</a></div><div class="footer-col"><h3>Planen</h3><a href="hotelinfos/">Hotelinformationen</a><a href="kontakt/">Kontakt & Anreise</a><a href="gruppen/">Feiern & Gruppen</a><a href="karriere/">Karriere</a><a href="'+BOOKING+'" target="_blank" rel="noopener">Direkt buchen</a></div><div class="footer-col"><h3>Kontakt</h3><p>Im Loh 14<br>78465 Konstanz-Litzelstetten</p><a href="tel:+49753194400">+49 7531 94400</a><a href="mailto:info@volapuek.de">info@volapuek.de</a><a href="https://www.instagram.com/hotelvolapuek/" target="_blank" rel="noopener">Instagram</a></div></div><div class="footer-bottom"><div class="footer-bottom__inner"><span>© 2026 Hotel-Restaurant Volapük GmbH · Konzeptwebsite von Hotelfreunde</span><span><a href="impressum/">Impressum</a> · <a href="datenschutz/">Datenschutz</a> · <a href="https://volapuek.de/agb/" target="_blank" rel="noopener">AGB</a></span></div></div></footer>'}
  document.querySelectorAll("site-header").forEach(function(el){el.outerHTML=header()});
  document.querySelectorAll("site-footer").forEach(function(el){el.outerHTML=footer()});
  var toggle=document.querySelector(".menu-toggle"),menu=document.querySelector(".main-nav");
  if(toggle&&menu)toggle.addEventListener("click",function(){var open=menu.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open));toggle.textContent=open?"Schließen":"Menü"});
  function lock(){
    var key="volapuek-demo-freigabe";try{if(localStorage.getItem(key)==="1")return}catch(e){}
    document.body.classList.add("locked");var el=document.createElement("div");el.className="demo-lock";el.setAttribute("role","dialog");el.setAttribute("aria-modal","true");
    el.innerHTML='<div class="demo-lock__card"><img class="demo-lock__logo" src="img/logo-volapuek.png" alt="Logo Hotel Volapük"><p class="eyebrow" style="color:#e3c3a4">Geschützte Konzeptvorschau</p><h1>Willkommen im Volapük.</h1><p>Diese Arbeitsprobe von Hotelfreunde ist nicht öffentlich. Bitte geben Sie das Vorschau-Passwort ein.</p><form><label class="skip-link" for="previewPassword">Passwort</label><input id="previewPassword" type="password" autocomplete="off" placeholder="Passwort" required><button type="submit">Vorschau öffnen</button></form><p class="demo-lock__error" role="alert">Das Passwort stimmt noch nicht.</p></div>';
    document.body.prepend(el);var form=el.querySelector("form"),input=el.querySelector("input"),err=el.querySelector(".demo-lock__error");setTimeout(function(){input.focus()},80);
    form.addEventListener("submit",function(ev){ev.preventDefault();var v=(input.value||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");if(v==="volapuek"||v==="volapuk"){try{localStorage.setItem(key,"1")}catch(e){}el.classList.add("is-leaving");document.body.classList.remove("locked");setTimeout(function(){el.remove()},480)}else{err.classList.add("show");input.select()}})
  }
  lock();
  var today=new Date();today.setHours(0,0,0,0);var tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);function iso(d){return d.toISOString().slice(0,10)}
  document.querySelectorAll("input[type=date]").forEach(function(i){i.min=iso(today);if(!i.value)i.value=iso(i.name==="departure"?tomorrow:today)});
  document.querySelectorAll(".booking-rail").forEach(function(form){form.addEventListener("submit",function(e){e.preventDefault();window.open(BOOKING,"_blank","noopener")})});
  var reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches,els=document.querySelectorAll(".reveal");if(reduced||!("IntersectionObserver" in window)){els.forEach(function(e){e.classList.add("in")})}else{var io=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add("in");io.unobserve(e.target)}})},{threshold:.08});els.forEach(function(e){io.observe(e)})}
})();
